
language: python
python:
  - '3.7.4'
stages:
  - test
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: test
      before_script: cd src/
      script:
        - python -m unittest discover